# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Check Python syntax
        run: python -m py_compile maths_utility.py
